sudo: required

language: java

jdk:
  - oraclejdk8

  services:
  - docker
  
before_install:
- cd easydao-samples/creating-sampledb
- ./build-image.sh
- ./run-container.sh

install: true

script: mvn clean install 

