sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker
  
before_install:
  - cd easydao-samples/creating-sampledb
  - docker build -t easydao-sampledb .
  - docker run --name sampledb -e POSTGRES_PASSWORD=sample -d easydao-sampledb

install: true

script: mvn clean install 
