sudo: required

services:
  - postgresql

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - stable

before_script:
  - psql -U postgres -a -f ./easydao-samples/creating-sampledb/initdb.sql
  - export PGPASSWORD="sample"

install:
  - mvn install:install-file -Dfile=./ojdbc5-11.1.0.7.0.jar -DgroupId=com.oracle -DartifactId=ojdbc5 -Dversion=11.1.0.7.0 -Dpackaging=jar
  - mvn install:install-file -Dfile=./orai18n-11.1.0.7.0.jar -DgroupId=com.oracle -DartifactId=orai18n -Dversion=11.1.0.7.0 -Dpackaging=jar

script: mvn clean install

notifications:
  slack: vanio-team:FY9RdQbjUkSOemSV8u1Atv6d
