sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - stable

before_script:
  - cd easydao-samples/creating-sampledb
  - docker build -t easydao-sampledb .
  - docker run --name sampledb -e POSTGRES_PASSWORD=sample -d easydao-sampledb
  - cd ../..
  - ip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' sampledb) && export DB_IP_ADDRESS=$ip
  - mvn install:install-file -Dfile=./ojdbc5-11.1.0.7.0.jar -DgroupId=com.oracle -DartifactId=ojdbc5 -Dversion=11.1.0.7.0 -Dpackaging=jar
  - mvn install:install-file -Dfile=./orai18n-11.1.0.7.0.jar -DgroupId=com.oracle -DartifactId=orai18n -Dversion=11.1.0.7.0 -Dpackaging=jar

install: true

script: mvn clean install

after_script:
  - cd easydao-samples/creating-sampledb
  - docker stop sampledb && docker rm sampledb && docker rmi easydao-sampledb

notifications:
  slack: vanio-team:FY9RdQbjUkSOemSV8u1Atv6d
